# Change these first
owner: InfraestructuraGTUCP # Your GitHub organization or username, where this repository lives
repo: estatus # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
    icon: https://www.google.com/favicon.ico
  - name: Universidad Católica de Pereira
    url: https://www.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/765f9c74c7b240e032e8e6d2829d2f8be33d8eba/assets/logo-vigi-black2.png
  - name: Portal Estudiante y Docente
    url: https://matriculas.ucp.edu.co/se
    icon: https://img.icons8.com/color/96/000000/classroom.png
  - name: UCP Virtual - Moodle
    url: https://www.ucpvirtual.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/ucpvirtual.png
  - name: Biblioteca CDCH
    url: https://biblioteca.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/bcdch.png
  - name: Intranet
    check: "tcp-ping"
    url: http://intranet.ucp.edu.co
    icon: https://img.icons8.com/color/96/000000/ms-share-point.png
  - name: QRFS
    url: https://qrsf.ucp.edu.co
    icon: https://img.icons8.com/color/96/000000/complaints.png
  - name: Mesa de Ayuda - HelpPeople
    check: "tcp-ping"
    url: https://mesadeayuda.ucp.edu.co
    icon: https://img.icons8.com/fluency/96/000000/help.png
assignees:
  - InfraestructuraGTUCP
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  theme: night
  baseUrl: /estatus
  logoUrl: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/da859f83229278e355d72f522317f6c52032c391/assets/logo-vigi-black.png
  favicon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/765f9c74c7b240e032e8e6d2829d2f8be33d8eba/assets/logo-vigi-black2.png
  name: Estatus U Católica Pei
  introTitle: "Página de estado y tiempo de actividad de los diferentes servicios web de la universidad"
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
   # - title: Estado
    #  href: https://infraestructuragtucp.github.io/estatus/
    #- title: GitHub
     # href: https://github.com/$OWNER/$REPO
i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  incidentReport: "Incidente n° $NUMBER Ver reporte →"
  activeIncidentSummary: Abierto a las $DATE con $POSTS publicaciones
  incidentTitle: Detalles de incidente n° $NUMBER
  incidentDetails: Detalles de incidente
  incidentFixed: Reparado
  incidentOngoing: En curso
  incidentOpenedAt: Abierto el
  incidentClosedAt: Cerrado el
  incidentSubscribe: Subscribirse a actualizaciones
  incidentViewOnGitHub: Ver en GitHub
  incidentCommentSummary: Publicado el $DATE por $AUTHOR
  incidentBack: ← Regresar a todos los incidentes
  pastIncidents: Incidentes anteriores
  pastIncidentsResolved: Resuelto en $MINUTES minutos, tiene $POSTS publicaciones
  liveStatus: Estado Actual
  overallUptime: "Estado general: $UPTIME"
  overallUptimeTitle: Estado actividad general
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta durante 7 días 
  responseTimeMs: Tiempo de respuesta (ms)
  up: Activo
  down: Caido
  degraded: Degradado
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: Esta página es un [recurso abierto]($REPO), desplegado por Gestión Tecnológica y desarrollado por [Upptime](https://upptime.js.org)
  scheduledMaintenance: Mantenimiento Programado
  scheduledMaintenanceSummaryStarted: Inició el $DATE durante $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia el $DATE durante $DURATION minutos
  startedAt: Comenzó el
  startsAt: inicia el
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Terminado
  incidentScheduled: Programado


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
