# Change these first
owner: InfraestructuraGTUCP # Your GitHub organization or username, where this repository lives
repo: estatus # The name of this repository

sites:
  - name: Universidad Católica de Pereira
    url: https://www.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/765f9c74c7b240e032e8e6d2829d2f8be33d8eba/assets/logo-vigi-black2.png
    
  - name: Portal Estudiante y Docente
    url: $PORTAL
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/portal.png
    
  - name: UCP Virtual - Moodle
    url: https://www.ucpvirtual.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/ucpvirtual.png
    
  - name: Biblioteca CDCH
    url: https://biblioteca.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/bcdch.png
    
  - name: Repositorio
    url: https://repositorio.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/bcdch.png
        
  - name: Intranet
    url: http://intranet.ucp.edu.co
    icon: https://img.icons8.com/color/96/000000/ms-share-point.png
    expectedStatusCodes:
    - 401
  - name: Booked
    url: $BOOKED
    icon: https://img.icons8.com/nolan/96/squared-menu.png
      
  - name: Múltiples Webs
    url: $MULTIPLESITES_UCP
    icon: https://img.icons8.com/nolan/96/squared-menu.png
    
  - name: QRSF
    url: https://qrsf.ucp.edu.co
    icon: https://img.icons8.com/color/96/000000/complaints.png
    
  - name: Mesa de Ayuda - HelpPeople
    url: $AYUDA
    icon: https://img.icons8.com/fluency/96/000000/help.png
    expectedStatusCodes:
    - 401
    
  - name: DNS 1
    check: "tcp-ping"
    url: w2k12r2-dns1.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/dns1.png
    port: 53
    
  - name: DNS 2
    check: "tcp-ping"
    url: w2k12r2-dns2.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/dns1.png
    port: 53
        
assignees:
  - InfraestructuraGTUCP
  
status-website:
  cname: estado.ucp.edu.co
  theme: night
  #baseUrl: /estatus
  logoUrl: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/da859f83229278e355d72f522317f6c52032c391/assets/logo-vigi-black.png
  favicon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/765f9c74c7b240e032e8e6d2829d2f8be33d8eba/assets/logo-vigi-black2.png
  name: Estado U Católica Pei
  introTitle: "#### Estado y tiempo de actividad de diferentes servicios web de la universidad"
  #introMessage:
  #navbar:
   # - title: Estado
    #  href: https://estado.ucp.edu.co
    #- title: GitHub
     # href: https://github.com/$OWNER/$REPO
     
i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  incidentReport: " #$NUMBER Ver detalles →"
  activeIncidentSummary: Sucedido el $DATE con $POSTS publicaciones
  incidentTitle: Detalles de incidente N° $NUMBER
  incidentDetails: Detalles del incidente
  incidentFixed: Solucionado
  incidentOngoing: En curso
  incidentOpenedAt: "Ocurrido el:"
  incidentClosedAt: "Finalizado el:"
  incidentSubscribe: " "
  incidentViewOnGitHub: " "
  incidentCommentSummary: Publicado el $DATE por $AUTHOR
  incidentBack: ← Volver
  pastIncidents: Incidentes anteriores
  pastIncidentsResolved: Resuelto en $MINUTES minutos, tiene $POSTS publicaciones
  liveStatus: Estado actual
  overallUptime: "Estado general: $UPTIME"
  overallUptimeTitle: Estado actividad general
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Tiempo de respuesta promedio
  sevelDayResponseTime: Tiempos de respuesta durante 7 días 
  responseTimeMs: Tiempo de respuesta (ms)
  up: Activo
  down: Caido
  degraded: Degradado
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: Este sitio es un recurso abierto, desplegado por Gestión Tecnológica y desarrollado por [Upptime](https://upptime.js.org)
  pastScheduledMaintenance: Anteriores mantenimientos programados
  scheduledMaintenance: Mantenimiento Programado
  scheduledMaintenanceSummaryStarted: Mantenimiento en curso con duración estimada de $DURATION minutos
  scheduledMaintenanceSummaryStarts: Programado para el **$DATE** y durará $DURATION minutos
  startedAt: "Comenzó el:"
  startsAt: "Programado para el:"
  duration: "Duración estimada de:"
  durationMin: $DURATION minutos
  incidentCompleted: Finalizado
  incidentScheduled: Programado
  #End
