# Change these first
owner: InfraestructuraGTUCP # Your GitHub organization or username, where this repository lives
repo: estatus # The name of this repository

sites:
  - name: Universidad Católica de Pereira
    url: https://www.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/765f9c74c7b240e032e8e6d2829d2f8be33d8eba/assets/logo-vigi-black2.png
  - name: Portal Estudiante y Docente
    url: $PORTAL
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/portal.png
  - name: UCP Virtual - Moodle
    url: https://www.ucpvirtual.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/ucpvirtual.png
  - name: Biblioteca CDCH
    url: https://biblioteca.ucp.edu.co
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/bcdch.png
  - name: Intranet
    expectedStatusCodes:
    - 401
    url: http://intranet.ucp.edu.co
    icon: https://img.icons8.com/color/96/000000/ms-share-point.png
  - name: Múltiples Webs
    url: $MULTIPLESITES_UCP
    icon: https://img.icons8.com/nolan/96/squared-menu.png
  - name: QRFS
    url: https://qrsf.ucp.edu.co
    icon: https://img.icons8.com/color/96/000000/complaints.png
  - name: Mesa de Ayuda - HelpPeople
    expectedStatusCodes:
    - 401
    url: $AYUDA
    icon: https://img.icons8.com/fluency/96/000000/help.png
  - name: DNS 1
    check: "tcp-ping"
    url: w2k12r2-dns1.ucp.edu.co
    port: 53
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/dns1.png
  - name: DNS 2
    check: "tcp-ping"
    url: w2k12r2-dns2.ucp.edu.co
    port: 53
    icon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/master/assets/dns2.png
assignees:
  - InfraestructuraGTUCP
status-website:
  cname: estado.ucp.edu.co
  theme: night
  #baseUrl: /estatus
  logoUrl: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/da859f83229278e355d72f522317f6c52032c391/assets/logo-vigi-black.png
  favicon: https://raw.githubusercontent.com/InfraestructuraGTUCP/estatus/765f9c74c7b240e032e8e6d2829d2f8be33d8eba/assets/logo-vigi-black2.png
  name: Estado U Católica Pei
  introTitle: "## Página de tiempo de actividad y estado de los diferentes servicios web de la universidad"
  #introMessage:
  navbar:
    - title: Estado
      href: https://estado.ucp.edu.co
    #- title: GitHub
     # href: https://github.com/$OWNER/$REPO
i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  incidentReport: "Incidente n° $NUMBER Ver reporte →"
  activeIncidentSummary: Abierto a las $DATE con $POSTS publicaciones
  incidentTitle: Detalles de incidente n° $NUMBER
  incidentDetails: Detalles de incidente
  incidentFixed: Reparado
  incidentOngoing: En curso
  incidentOpenedAt: Abierto el
  incidentClosedAt: Cerrado el
  incidentSubscribe: Subscribirse a actualizaciones
  incidentViewOnGitHub: Ver en GitHub
  incidentCommentSummary: Publicado el $DATE por $AUTHOR
  incidentBack: ← Regresar a todos los incidentes
  pastIncidents: Incidentes anteriores
  pastIncidentsResolved: Resuelto en $MINUTES minutos, tiene $POSTS publicaciones
  liveStatus: Estado actual
  overallUptime: "Estado general: $UPTIME"
  overallUptimeTitle: Estado actividad general
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: Tiempos de respuesta durante 7 días 
  responseTimeMs: Tiempo de respuesta (ms)
  up: Activo
  down: Caido
  degraded: Degradado
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: Esta página es un recurso abierto, desplegado por Gestión Tecnológica y desarrollado por [Upptime](https://upptime.js.org)
  pastScheduledMaintenance: Anteriores mantenimientos programados
  scheduledMaintenance: Mantenimiento Programado
  scheduledMaintenanceSummaryStarted: Inició el $DATE durante $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia el $DATE durante $DURATION minutos
  startedAt: Comenzó el
  startsAt: inicia el
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Terminado
  incidentScheduled: Programado
